import express from 'express'
import cors from 'cors'
import { chromium } from 'playwright'
import { spawn, execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { join, resolve, basename } from 'node:path'
import { randomUUID } from 'node:crypto'
import { scryptSync, timingSafeEqual } from 'node:crypto'
import { hostname, platform } from 'node:os'

const exec = promisify(execFile)
const root = resolve(process.cwd())
const dataDir = join(root, 'data'), testsDir = join(dataDir, 'tests'), reportsDir = join(dataDir, 'reports')
for (const dir of [dataDir, testsDir, reportsDir]) if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
const dbFile = join(dataDir, 'sentinel.json')
type DB = { projects:any[]; tests:any[]; runs:any[]; jobs:any[]; runners:any[]; users:any[]; sessions:any[]; settings?:any }
const load = ():DB => {const raw=existsSync(dbFile)?JSON.parse(readFileSync(dbFile,'utf8')):{};return{projects:raw.projects||[],tests:raw.tests||[],runs:raw.runs||[],jobs:raw.jobs||[],runners:raw.runners||[],users:raw.users||[],sessions:raw.sessions||[],settings:raw.settings||{syncReports:true,syncScreenshots:true}}}
const save = (db:DB) => writeFileSync(dbFile, JSON.stringify(db,null,2))
const safeName = (s:string) => s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9-_]+/g,'-').replace(/^-|-$/g,'').toLowerCase()
async function gitInfo(path:string){if(!path||!existsSync(path))return{branch:'',commit:''};try{const [{stdout:branch},{stdout:commit}]=await Promise.all([exec('git',['branch','--show-current'],{cwd:path}),exec('git',['rev-parse','--short','HEAD'],{cwd:path})]);return{branch:branch.trim(),commit:commit.trim()}}catch{return{branch:'',commit:''}}}
async function online(url:string){try{const c=new AbortController();setTimeout(()=>c.abort(),1800);const r=await fetch(url,{signal:c.signal});return r.status<500?'online':'offline'}catch{return'offline'}}

const app=express();app.use(cors());app.use(express.json({limit:'50mb'}));app.use('/reports',express.static(reportsDir))
const hashPassword=(password:string,salt:string)=>scryptSync(password,salt,64).toString('hex')
app.get('/api/auth/status',(_req,res)=>res.json({configured:load().users.length>0}))
app.post('/api/auth/setup',(req,res)=>{const db=load();if(db.users.length)return res.status(409).json({error:'Workspace já configurado'});const {name,email,password,workspace='QA Workspace'}=req.body;if(!name||!email||!password||password.length<8)return res.status(400).json({error:'Informe nome, e-mail e senha com pelo menos 8 caracteres'});const salt=randomUUID(),user={id:randomUUID(),name,email:String(email).toLowerCase(),role:'admin',salt,passwordHash:hashPassword(password,salt),createdAt:new Date().toISOString()},token=randomUUID()+randomUUID();db.users.push(user);db.sessions.push({token,userId:user.id,createdAt:new Date().toISOString()});db.settings={...db.settings,workspace};save(db);res.status(201).json({token,user:{id:user.id,name:user.name,email:user.email,role:user.role},workspace})})
app.post('/api/auth/login',(req,res)=>{const db=load(),user=db.users.find(u=>u.email===String(req.body.email||'').toLowerCase());if(!user)return res.status(401).json({error:'E-mail ou senha inválidos'});const candidate=Buffer.from(hashPassword(String(req.body.password||''),user.salt),'hex'),stored=Buffer.from(user.passwordHash,'hex');if(candidate.length!==stored.length||!timingSafeEqual(candidate,stored))return res.status(401).json({error:'E-mail ou senha inválidos'});const token=randomUUID()+randomUUID();db.sessions.push({token,userId:user.id,createdAt:new Date().toISOString()});save(db);res.json({token,user:{id:user.id,name:user.name,email:user.email,role:user.role},workspace:db.settings?.workspace})})
app.use('/api',(req,res,next)=>{if(req.path.startsWith('/auth/')||req.path.startsWith('/runner/heartbeat')||req.path.startsWith('/runner/jobs/'))return next();const token=String(req.headers.authorization||'').replace(/^Bearer /,'');const db=load(),session=db.sessions.find(s=>s.token===token);if(!session)return res.status(401).json({error:'Sessão necessária'});(req as any).userId=session.userId;next()})
app.get('/api/projects',async(_req,res)=>{const db=load();db.projects=await Promise.all(db.projects.map(async p=>({...p,...await gitInfo(p.repoPath),status:await online(p.url)})));save(db);res.json(db.projects)})
app.post('/api/projects',async(req,res)=>{const {name,url,repoPath='',referenceUrl='',sourceMode='local',environmentName}=req.body;if(!name||!url)return res.status(400).json({error:'Nome e URL são obrigatórios'});if(!['local','remote'].includes(sourceMode))return res.status(400).json({error:'Tipo de ambiente inválido'});if(sourceMode==='local'&&!repoPath)return res.status(400).json({error:'Informe a pasta do projeto local'});try{new URL(url);if(referenceUrl)new URL(referenceUrl)}catch{return res.status(400).json({error:'Informe URLs válidas'})}const db=load(),git=sourceMode==='local'?await gitInfo(repoPath):{branch:'',commit:''};const p={id:randomUUID(),name,url,repoPath:sourceMode==='local'?repoPath:'',referenceUrl,sourceMode,environmentName:environmentName||(sourceMode==='remote'?'Staging':'Local'),...git,status:await online(url),createdAt:new Date().toISOString()};db.projects.unshift(p);save(db);res.status(201).json(p)})
app.get('/api/tests',(_req,res)=>res.json(load().tests))
app.put('/api/tests/:id',(req,res)=>{const db=load(),i=db.tests.findIndex(t=>t.id===req.params.id);if(i<0)return res.status(404).json({error:'Teste não encontrado'});db.tests[i]={...db.tests[i],name:req.body.name,code:req.body.code,updatedAt:new Date().toISOString()};writeFileSync(join(testsDir,`${db.tests[i].id}.spec.ts`),db.tests[i].code);save(db);res.json(db.tests[i])})
app.get('/api/runs',(_req,res)=>res.json(load().runs.sort((a,b)=>b.startedAt.localeCompare(a.startedAt))))
const fallbackRunner=()=>({id:'local-runner',name:'Runner local',platform:'unknown',hostname:'Nenhum dispositivo',status:'offline',version:'0.3.0',lastSeen:'',capabilities:['Playwright','Git','Screenshots','Relatórios']})
app.get('/api/runner',(_req,res)=>{const db=load(),runner=db.runners.sort((a,b)=>b.lastSeen.localeCompare(a.lastSeen))[0];res.json(runner?{...runner,status:Date.now()-new Date(runner.lastSeen).getTime()<15000?'online':'offline'}:fallbackRunner())})
app.post('/api/runner/sync',(_req,res)=>{const db=load();db.jobs.push({id:randomUUID(),type:'sync',status:'pending',createdAt:new Date().toISOString(),payload:{}});save(db);res.json({message:'Sincronização solicitada'})})
async function commandAvailable(command:string){try{await exec(process.platform==='win32'?'where.exe':'which',[command]);return true}catch{return false}}
app.get('/api/integrations',async(_req,res)=>{const db=load(),latest=db.runners.sort((a,b)=>b.lastSeen.localeCompare(a.lastSeen))[0],fresh=latest&&Date.now()-new Date(latest.lastSeen).getTime()<15000;const claude=!!(fresh&&latest.integrations?.claude),codex=!!(fresh&&latest.integrations?.codex);res.json([{id:'claude',name:'Claude Code',kind:'claude',status:claude?'online':'offline',detail:claude?'Autenticado no Runner local':'Instale ou conecte o Claude Code no Runner',recommended:true},{id:'codex',name:'OpenAI Codex',kind:'codex',status:codex?'online':'offline',detail:codex?'Disponível no Runner local':'Codex não detectado no Runner'},{id:'local',name:'Explorador local',kind:'local',status:fresh?'online':'offline',detail:'Regras de navegação sem custo de API'}])})
app.post('/api/integrations/:id/configure',async(req,res)=>{const id=req.params.id;if(id==='claude'){const ok=await commandAvailable('claude');return res.json({message:ok?'Claude Code detectado e pronto para uso':'Claude Code não foi encontrado. Instale e autentique-o neste computador.'})}if(id==='codex'){const ok=await commandAvailable('codex');return res.json({message:ok?'Codex detectado e pronto para uso':'Codex CLI não foi encontrado neste ambiente.'})}res.json({message:'Explorador local já está configurado.'})})
const runnerToken=process.env.SENTINEL_RUNNER_TOKEN||'sentinel-local-dev-token'
const runnerAuth=(req:any,res:any,next:any)=>req.headers.authorization===`Bearer ${runnerToken}`?next():res.status(401).json({error:'Runner não autorizado'})
app.post('/api/runner/heartbeat',runnerAuth,(req,res)=>{const db=load(),incoming={...req.body,lastSeen:new Date().toISOString(),status:'online'};const i=db.runners.findIndex(r=>r.id===incoming.id);if(i>=0)db.runners[i]={...db.runners[i],...incoming};else db.runners.push(incoming);save(db);res.json({ok:true,serverTime:new Date().toISOString()})})
app.get('/api/runner/jobs/next',runnerAuth,(_req,res)=>{const db=load(),job=db.jobs.find(j=>j.status==='pending');if(!job)return res.status(204).end();job.status='claimed';job.claimedAt=new Date().toISOString();save(db);res.json(job)})
app.post('/api/runner/jobs/:id/complete',runnerAuth,(req,res)=>{const db=load(),job=db.jobs.find(j=>j.id===req.params.id);if(!job)return res.status(404).json({error:'Trabalho não encontrado'});job.status='complete';job.completedAt=new Date().toISOString();job.result={status:req.body.status,summary:req.body.summary};if(req.body.test){const now=new Date().toISOString(),test={...req.body.test,createdAt:now,updatedAt:now};db.tests.unshift(test);writeFileSync(join(testsDir,`${test.id}.spec.ts`),test.code)}if(job.runId){const i=db.runs.findIndex(r=>r.id===job.runId);if(i>=0)db.runs[i]={...db.runs[i],status:req.body.status||'failed',summary:req.body.summary||'',duration:req.body.duration||0,reportPath:req.body.reportHtml?`/reports/${job.runId}/index.html`:undefined};if(req.body.reportHtml){const dir=join(reportsDir,job.runId);mkdirSync(dir,{recursive:true});writeFileSync(join(dir,'index.html'),req.body.reportHtml);for(const a of req.body.artifacts||[]){if(/^[a-zA-Z0-9_.-]+$/.test(a.name))writeFileSync(join(dir,a.name),Buffer.from(a.content,'base64'))}}}save(db);res.json({ok:true})})

app.post('/api/projects/:id/record',async(req,res)=>{const db=load(),p=db.projects.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Projeto não encontrado'});db.jobs.push({id:randomUUID(),type:'record',status:'pending',createdAt:new Date().toISOString(),payload:{project:p,testId:randomUUID()}});save(db);res.json({message:'Gravação enviada ao Runner. A janela abrirá neste dispositivo.'})})

app.post('/api/tests/:id/run',async(req,res)=>{const db=load(),t=db.tests.find(x=>x.id===req.params.id),p=db.projects.find(x=>x.id===t?.projectId);if(!t||!p)return res.status(404).json({error:'Teste ou projeto não encontrado'});const git=await gitInfo(p.repoPath),run={id:randomUUID(),projectId:p.id,testId:t.id,type:'fixed',status:'running',startedAt:new Date().toISOString(),...git};db.runs.unshift(run);db.jobs.push({id:randomUUID(),runId:run.id,type:'fixed',status:'pending',createdAt:new Date().toISOString(),payload:{project:p,test:t}});save(db);res.json(run)})
async function runFixed(run:any,t:any,p:any){const out=join(reportsDir,run.id);mkdirSync(out,{recursive:true});const file=join(testsDir,`${t.id}.spec.ts`);writeFileSync(file,t.code);const started=Date.now();try{await exec(process.platform==='win32'?'npx.cmd':'npx',['playwright','test',file,'--reporter=html'],{cwd:root,env:{...process.env,PLAYWRIGHT_HTML_OUTPUT_DIR:out,PLAYWRIGHT_HTML_OPEN:'never'},maxBuffer:4e6});finishRun(run.id,'passed',Date.now()-started,`Todos os passos de “${t.name}” funcionaram.`,out)}catch(e:any){writeFileSync(join(out,'error.txt'),String(e?.stdout||e?.stderr||e));finishRun(run.id,'failed',Date.now()-started,'O fluxo apresentou uma falha. Consulte o relatório para reproduzir.',out)}}

app.post('/api/projects/:id/explore',async(req,res)=>{const db=load(),p=db.projects.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Projeto não encontrado'});const git=await gitInfo(p.repoPath),run={id:randomUUID(),projectId:p.id,type:'explore',status:'running',startedAt:new Date().toISOString(),mission:req.body.mission,minutes:req.body.minutes,...git};db.runs.unshift(run);db.jobs.push({id:randomUUID(),runId:run.id,type:'explore',status:'pending',createdAt:new Date().toISOString(),payload:{project:p,mission:req.body.mission,minutes:req.body.minutes}});save(db);res.json(run)})
async function explore(run:any,p:any){const dir=join(reportsDir,run.id);mkdirSync(dir,{recursive:true});const issues:any[]=[];let browser;const started=Date.now();try{browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('console',m=>{if(m.type()==='error')issues.push({kind:'Console',severity:'Alta',detail:m.text(),url:page.url()})});page.on('response',r=>{if(r.status()>=400)issues.push({kind:'Rede',severity:r.status()>=500?'Alta':'Média',detail:`${r.status()} ${r.request().method()} ${r.url()}`,url:page.url()})});await page.goto(p.url,{waitUntil:'domcontentloaded',timeout:20000});await page.screenshot({path:join(dir,'pagina-inicial.png'),fullPage:true});const title=await page.title();if(!title)issues.push({kind:'Acessibilidade',severity:'Baixa',detail:'A página não possui título.',url:page.url()});const imgs=await page.locator('img').count();for(let i=0;i<imgs;i++){const alt=await page.locator('img').nth(i).getAttribute('alt');if(alt===null)issues.push({kind:'Acessibilidade',severity:'Baixa',detail:`Imagem ${i+1} sem texto alternativo.`,url:page.url()})}const links=await page.locator('a[href]').evaluateAll((els:any[])=>els.map(e=>({text:(e.textContent||'').trim(),href:e.href})).filter(x=>x.href));const local=[...new Map(links.filter((x:any)=>{try{return new URL(x.href).origin===new URL(p.url).origin}catch{return false}}).map((x:any)=>[x.href,x])).values()].slice(0,12) as any[];for(let i=0;i<local.length;i++){try{const pg=await browser.newPage({viewport:{width:i%2?390:1440,height:844}});pg.on('console',m=>{if(m.type()==='error')issues.push({kind:'Console',severity:'Alta',detail:m.text(),url:pg.url()})});const response=await pg.goto(local[i].href,{waitUntil:'domcontentloaded',timeout:12000});if(response&&response.status()>=400)issues.push({kind:'Navegação',severity:'Alta',detail:`Link “${local[i].text||local[i].href}” retornou ${response.status()}.`,url:local[i].href});await pg.screenshot({path:join(dir,`pagina-${i+1}.png`),fullPage:true});await pg.close()}catch(e:any){issues.push({kind:'Navegação',severity:'Média',detail:`Não foi possível abrir ${local[i].href}: ${e.message}`,url:local[i].href})}}await browser.close();const status=issues.some(i=>i.severity==='Alta')?'failed':'passed';writeReport(dir,p,run,issues,{title,pages:local.length+1});finishRun(run.id,status,Date.now()-started,issues.length?`${issues.length} possível(is) problema(s) encontrado(s).`:'Nenhum problema evidente foi encontrado na exploração inicial.',dir)}catch(e:any){if(browser)await browser.close().catch(()=>{});issues.push({kind:'Execução',severity:'Alta',detail:e.message,url:p.url});writeReport(dir,p,run,issues,{title:'Falha na exploração',pages:0});finishRun(run.id,'failed',Date.now()-started,'A exploração não conseguiu concluir.',dir)}}
function esc(s:any){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}
function writeReport(dir:string,p:any,run:any,issues:any[],meta:any){const shots=readdirSync(dir).filter(x=>x.endsWith('.png'));const html=`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Relatório Sentinel — ${esc(p.name)}</title><style>body{font:14px system-ui;background:#f6f6fa;color:#20202b;margin:0}main{max-width:1050px;margin:auto;padding:40px}.hero,.card{background:white;border:1px solid #e4e3ea;border-radius:14px;padding:24px;margin-bottom:16px}h1{margin:0 0 8px}.meta{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.meta div{background:#f5f3ff;padding:12px;border-radius:8px}.meta small,.meta b{display:block}.meta small{color:#777;margin-bottom:4px}.issue{border-left:4px solid #f06b5d}.issue.Média{border-color:#e9a340}.issue.Baixa{border-color:#5b9ee8}code{background:#eee;padding:3px}.shots{display:grid;grid-template-columns:repeat(2,1fr);gap:15px}.shots img{width:100%;border:1px solid #ddd;border-radius:8px}@media(max-width:700px){.meta,.shots{grid-template-columns:1fr}}</style><main><section class="hero"><p>SENTINEL QA STUDIO</p><h1>${esc(p.name)}</h1><p>${esc(run.mission)}</p><div class="meta"><div><small>URL</small><b>${esc(p.url)}</b></div><div><small>Branch</small><b>${esc(run.branch||'—')}</b></div><div><small>Commit</small><b>${esc(run.commit||'—')}</b></div><div><small>Páginas visitadas</small><b>${meta.pages}</b></div></div></section><h2>Descobertas (${issues.length})</h2>${issues.length?issues.map(i=>`<section class="card issue ${esc(i.severity)}"><b>${esc(i.severity)} · ${esc(i.kind)}</b><p>${esc(i.detail)}</p><small>${esc(i.url)}</small></section>`).join(''):'<section class="card"><b>Nenhum problema evidente encontrado</b><p>A exploração automática concluiu sem erros de console, rede ou navegação.</p></section>'}<h2>Evidências</h2><div class="shots">${shots.map(s=>`<a href="${s}"><img src="${s}" alt="Evidência"></a>`).join('')}</div></main></html>`;writeFileSync(join(dir,'index.html'),html)}
function finishRun(id:string,status:string,duration:number,summary:string,dir:string){const db=load(),i=db.runs.findIndex(r=>r.id===id);if(i>=0){db.runs[i]={...db.runs[i],status,duration,summary,reportPath:`/reports/${basename(dir)}/index.html`};save(db)}}
const distDir=join(root,'dist');if(existsSync(distDir)){app.use(express.static(distDir));app.use((req,res,next)=>{if(req.method==='GET'&&!req.path.startsWith('/api')&&!req.path.startsWith('/reports'))return res.sendFile(join(distDir,'index.html'));next()})}
const port=Number(process.env.PORT||4311);app.listen(port,()=>console.log(`Sentinel Cloud: http://localhost:${port}`))
