import { chromium } from 'playwright'
import { spawn, execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { hostname, platform } from 'node:os'
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import pixelmatch from 'pixelmatch'
import { PNG } from 'pngjs'

const exec=promisify(execFile),root=resolve(process.cwd()),work=join(root,'.runner-work')
if(!existsSync(work))mkdirSync(work,{recursive:true})
const cloud=process.env.SENTINEL_CLOUD_URL||'http://localhost:4311',token=process.env.SENTINEL_RUNNER_TOKEN||'sentinel-local-dev-token'
const headers={'Content-Type':'application/json','Authorization':`Bearer ${token}`}
async function available(cmd:string){try{await exec(process.platform==='win32'?'where.exe':'which',[cmd]);return true}catch{return false}}
async function capabilities(){const [claude,codex]=await Promise.all([available('claude'),available('codex')]);return{tools:['Playwright','Git','Screenshots','Relatórios'],integrations:{claude,codex,local:true}}}
async function heartbeat(){try{const caps=await capabilities();await fetch(`${cloud}/api/runner/heartbeat`,{method:'POST',headers,body:JSON.stringify({id:`${hostname()}-runner`,name:'Runner deste dispositivo',hostname:hostname(),platform:platform(),version:'0.3.0',capabilities:caps.tools,integrations:caps.integrations})})}catch{}}
async function complete(id:string,data:any){await fetch(`${cloud}/api/runner/jobs/${id}/complete`,{method:'POST',headers,body:JSON.stringify(data)})}
function artifact(path:string){return{name:path.split(/[\\/]/).pop(),content:readFileSync(path).toString('base64')}}
function esc(v:any){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}
function report(project:any,title:string,summary:string,issues:any[],shots:string[],context:any){return`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(title)}</title><style>body{font:14px system-ui;background:#f5f6fa;color:#20202b;margin:0}main{max-width:1050px;margin:auto;padding:40px}.hero,.card{background:#fff;border:1px solid #e5e4eb;border-radius:14px;padding:24px;margin-bottom:15px}.meta{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.meta div{background:#f3f0ff;padding:12px;border-radius:8px}.meta small,.meta b{display:block}.issue{border-left:4px solid #ef6a5d}.issue.Média{border-color:#e5a344}.issue.Baixa{border-color:#559be0}.shots{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.shots img{width:100%;border-radius:8px;border:1px solid #ddd}code{background:#eee;padding:3px}</style><main><section class="hero"><small>SENTINEL QA CLOUD · EXECUÇÃO LOCAL</small><h1>${esc(title)}</h1><p>${esc(summary)}</p><div class="meta"><div><small>Projeto</small><b>${esc(project.name)}</b></div><div><small>Branch</small><b>${esc(context.branch||'—')}</b></div><div><small>Commit</small><b>${esc(context.commit||'—')}</b></div><div><small>Runner</small><b>${esc(hostname())}</b></div></div></section><h2>Descobertas (${issues.length})</h2>${issues.length?issues.map(i=>`<section class="card issue ${esc(i.severity)}"><b>${esc(i.severity)} · ${esc(i.kind)}</b><p>${esc(i.detail)}</p><small>${esc(i.url)}</small></section>`).join(''):'<section class="card"><b>Nenhum problema evidente</b><p>A execução foi concluída sem descobertas.</p></section>'}<h2>Evidências</h2><div class="shots">${shots.map(s=>`<img src="${s.split(/[\\/]/).pop()}" alt="Evidência">`).join('')}</div></main></html>`}
async function git(path:string){if(!path||!existsSync(path))return{};try{const [{stdout:branch},{stdout:commit}]=await Promise.all([exec('git',['branch','--show-current'],{cwd:path}),exec('git',['rev-parse','--short','HEAD'],{cwd:path})]);return{branch:branch.trim(),commit:commit.trim()}}catch{return{}}}
async function record(job:any){const {project,testId}=job.payload,file=join(work,`${testId}.spec.ts`),bin=process.platform==='win32'?'npx.cmd':'npx';await new Promise<void>((ok,fail)=>{const child=spawn(bin,['playwright','codegen',project.url,'--output',file,'--target','playwright-test'],{cwd:root,stdio:'ignore',windowsHide:false});child.on('exit',()=>ok());child.on('error',fail)});if(!existsSync(file))return complete(job.id,{status:'failed',summary:'A gravação foi fechada sem gerar passos.'});const code=readFileSync(file,'utf8');return complete(job.id,{status:'passed',summary:'Fluxo gravado e sincronizado.',test:{id:testId,projectId:project.id,name:`Fluxo gravado ${new Date().toLocaleString('pt-BR')}`,code}})}
async function fixed(job:any){const {project,test}=job.payload,dir=join(work,job.id);mkdirSync(dir,{recursive:true});const file=join(dir,`${test.id}.spec.ts`);writeFileSync(file,test.code);const started=Date.now(),context=await git(project.repoPath),issues:any[]=[];let status='passed',summary=`Todos os passos de “${test.name}” funcionaram.`;try{await exec(process.platform==='win32'?'npx.cmd':'npx',['playwright','test',file,'--reporter=line'],{cwd:root,maxBuffer:4e6})}catch(e:any){status='failed';summary='O fluxo apresentou uma falha.';issues.push({kind:'Regressão',severity:'Alta',detail:String(e.stdout||e.stderr||e).slice(0,4000),url:project.url})}return complete(job.id,{status,summary,duration:Date.now()-started,reportHtml:report(project,test.name,summary,issues,[],context),artifacts:[]})}
async function claudeAnalysis(snapshot:string,mission:string){if(!await available('claude'))return'';try{const prompt=`Você é um QA exploratório. Analise este resumo de interface e a missão. Liste de forma curta possíveis riscos e casos adicionais, sem executar ações. Missão: ${mission}\nInterface: ${snapshot.slice(0,12000)}`;const {stdout}=await exec('claude',['-p',prompt,'--output-format','text','--max-turns','1'],{timeout:90000,maxBuffer:2e6});return stdout.trim()}catch{return''}}
async function visualCompare(browser:any,page:any,referenceUrl:string,dir:string,issues:any[],shots:string[]){const current=join(dir,'comparacao-atual.png'),reference=join(dir,'comparacao-referencia.png'),diffPath=join(dir,'comparacao-diferencas.png');await page.screenshot({path:current,fullPage:false});const ref=await browser.newPage({viewport:{width:1440,height:900}});await ref.goto(referenceUrl,{waitUntil:'networkidle',timeout:25000});await ref.screenshot({path:reference,fullPage:false});await ref.close();const a=PNG.sync.read(readFileSync(current)),b=PNG.sync.read(readFileSync(reference));if(a.width!==b.width||a.height!==b.height)return;const diff=new PNG({width:a.width,height:a.height}),changed=pixelmatch(a.data,b.data,diff.data,a.width,a.height,{threshold:.15,includeAA:false}),ratio=changed/(a.width*a.height)*100;PNG.sync.write(diff);writeFileSync(diffPath,PNG.sync.write(diff));shots.push(current,reference,diffPath);if(ratio>1)issues.push({kind:'Comparação Lovable',severity:ratio>25?'Média':'Baixa',detail:`A tela inicial possui ${ratio.toFixed(1)}% de diferença visual em relação ao modelo cadastrado. Consulte a imagem de diferenças antes de classificar como erro.`,url:referenceUrl})}
async function explore(job:any){const {project,mission}=job.payload,dir=join(work,job.id);mkdirSync(dir,{recursive:true});const started=Date.now(),context=await git(project.repoPath),issues:any[]=[],shots:string[]=[];let browser:any;try{browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('console',(m:any)=>{if(m.type()==='error')issues.push({kind:'Console',severity:'Alta',detail:m.text(),url:page.url()})});page.on('response',(r:any)=>{if(r.status()>=400)issues.push({kind:'Rede',severity:r.status()>=500?'Alta':'Média',detail:`${r.status()} ${r.request().method()} ${r.url()}`,url:page.url()})});await page.goto(project.url,{waitUntil:'domcontentloaded',timeout:20000});const first=join(dir,'pagina-inicial.png');await page.screenshot({path:first,fullPage:true});shots.push(first);if(project.referenceUrl)await visualCompare(browser,page,project.referenceUrl,dir,issues,shots).catch((e:any)=>issues.push({kind:'Comparação Lovable',severity:'Baixa',detail:`Não foi possível comparar: ${e.message}`,url:project.referenceUrl}));const snapshot=await page.locator('body').innerText().catch(()=>''),links=await page.locator('a[href]').evaluateAll((els:any[])=>els.map(e=>({text:(e.textContent||'').trim(),href:e.href})));const local=[...new Map(links.filter((x:any)=>{try{return new URL(x.href).origin===new URL(project.url).origin}catch{return false}}).map((x:any)=>[x.href,x])).values()].slice(0,10) as any[];for(let i=0;i<local.length;i++){try{const p=await browser.newPage({viewport:{width:i%2?390:1440,height:844}});const r=await p.goto(local[i].href,{waitUntil:'domcontentloaded',timeout:12000});if(r&&r.status()>=400)issues.push({kind:'Navegação',severity:'Alta',detail:`Link retornou ${r.status()}.`,url:local[i].href});const shot=join(dir,`pagina-${i+1}.png`);await p.screenshot({path:shot,fullPage:true});shots.push(shot);await p.close()}catch(e:any){issues.push({kind:'Navegação',severity:'Média',detail:e.message,url:local[i].href})}}const insight=await claudeAnalysis(snapshot,mission);if(insight)issues.push({kind:'Análise Claude',severity:'Baixa',detail:insight,url:project.url});await browser.close();const status=issues.some(i=>i.severity==='Alta')?'failed':'passed',summary=issues.length?`${issues.length} possível(is) problema(s) ou sugestão(ões).`:'Nenhum problema evidente encontrado.';return complete(job.id,{status,summary,duration:Date.now()-started,reportHtml:report(project,'Exploração inteligente',summary,issues,shots,context),artifacts:shots.map(artifact)})}catch(e:any){if(browser)await browser.close().catch(()=>{});const summary='A exploração não conseguiu concluir.';issues.push({kind:'Execução',severity:'Alta',detail:e.message,url:project.url});return complete(job.id,{status:'failed',summary,duration:Date.now()-started,reportHtml:report(project,'Exploração inteligente',summary,issues,shots,context),artifacts:shots.map(artifact)})}}
async function workJob(job:any){if(job.type==='record')return record(job);if(job.type==='fixed')return fixed(job);if(job.type==='explore')return explore(job);return complete(job.id,{status:'passed',summary:'Runner sincronizado.'})}
let busy=false
async function poll(){if(busy)return;try{const r=await fetch(`${cloud}/api/runner/jobs/next`,{headers});if(r.status===204)return;if(!r.ok)return;busy=true;await workJob(await r.json())}catch(e){console.error('Runner:',(e as Error).message)}finally{busy=false}}
console.log(`Sentinel Runner ${hostname()} conectado a ${cloud}`)
await heartbeat();setInterval(heartbeat,5000);setInterval(poll,1500)
